service: quickbooks-oauth

provider:
  name: aws
  runtime: nodejs12.x

  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda: '*'
      Resource:
        - '*'

  stage: ${env:STAGE}
  region: ${env:REGION}
  role: ${env:ROLE}

functions:
  quickbooks_oauth:
    handler: index.handler
    timeout: 500
    events:
      - schedule: rate(1 hour)

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
